export default {
    SET_FIRSTNAME: "SET_FIRSTNAME",
    SET_LASTNAME: "SET_LASTNAME",
    SET_EMAIL: "SET_EMAIL",
    SET_MOBILE_NUMBER: "SET_MOBILE_NUMBER",
    SET_PASSWORD: "SET_PASSWORD",
    SET_REGISTER_STATUS: "SET_REGISTER_STATUS",
    SET_LOADING_STATUS: "SET_LOADING_STATUS",
    CLEAR_INPUT: "CLEAR_INPUT"
};