export default {
    SET_CURRENT_BOOKING: "SET_CURRENT_BOOKING",
    UPDATE_BOOKING: "UPDATE_BOOKING",
    UPDATE_LOADER: "UPDATE_LOADER",
    UPDATE_BOOKING_HISTORY: "UPDATE_BOOKING_HISTORY",
    SHOW_DRIVER: "SHOW_DRIVER",
    SHOW_RATING_MODAL: "SHOW_RATING_MODAL",
    SHOW_MAP_TRACK_MODAL: "SHOW_MAP_TRACK_MODAL",
    SET_SELECTED_STAR: "SET_SELECTED_STAR",
    GET_COMMENT: "GET_COMMENT",
    UPDATE_DRIVER_LOCATION: "UPDATE_DRIVER_LOCATION"
};