export default {
    GET_USERNAME: "GET_USERNAME",
    GET_PASSWORD: "GET_PASSWORD",
    LOGIN: "LOGIN",
    UPDATE_LOADING_STATUS: "UPDATE_LOADING_STATUS",
    SET_ACCOUNT: "SET_ACCOUNT",
    CLEAR_INPUTS: "CLEAR_INPUTS",
    SET_LOGIN_PREFERENCE: "SET_LOGIN_PREFERENCE",
    SHOW_FORGOT_PASSWORD_MODAL: "SHOW_FORGOT_PASSWORD_MODAL"
};