export default {
    GET_USERNAME: "GET_USERNAME",
    GET_PASSWORD: "GET_PASSWORD",
    LOGIN: "LOGIN",
    UPDATE_LOADING_STATUS: "UPDATE_LOADING_STATUS",
    SET_ACCOUNT: "SET_ACCOUNT",
    CLEAR_INPUTS: "CLEAR_INPUTS"
};