export default {
    ADD_ADDITIONAL_PRICE: "ADD_ADDITIONAL_PRICE",
    REMOVE_ADDITIONAL_PRICE: "REMOVE_ADDITIONAL_PRICE",
    GET_ADDITIONAL_SERVICES: "GET_ADDITIONAL_SERVICES",
    REMOVE_ADDITIONAL_SERVICES: "REMOVE_ADDITIONAL_SERVICES",
    ADDITIONAL_SERVICE_1: "ADDITIONAL_SERVICE_1",
    ADDITIONAL_SERVICE_2: "ADDITIONAL_SERVICE_2",
    ADDITIONAL_SERVICE_3: "ADDITIONAL_SERVICE_3",
    ADDITIONAL_SERVICE_4: "ADDITIONAL_SERVICE_4",
    ADDITIONAL_SERVICE_5: "ADDITIONAL_SERVICE_5",
    ADDITIONAL_SERVICE_6: "ADDITIONAL_SERVICE_6",
    UPDATE_ADDITIONAL_SERVICE: "UPDATE_ADDITIONAL_SERVICE",
    SET_PICKUP_DATE_TIME: "SET_PICKUP_DATE_TIME",
    SET_BOOKING_NOTE: "SET_BOOKING_NOTE"
};